- docs/_config.yml
Change fields to reflect Productiv
> Update _config.yml 

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/deliverable/AddCommand.java
- src/main/java/seedu/address/logic/commands/deliverable/DeleteCommand.java
- src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
- src/main/java/seedu/address/logic/parser/deliverable/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/deliverable/CliSyntax.java
- src/main/java/seedu/address/logic/parser/deliverable/DeleteCommandParser.java
- src/main/java/seedu/address/logic/parser/deliverable/DeliverableBookParser.java
- src/main/java/seedu/address/logic/parser/deliverable/ParserUtil.java
- src/main/java/seedu/address/logic/parser/person/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/person/CliSyntax.java
- src/main/java/seedu/address/model/deliverable/deliverable/Deadline.java
- src/main/java/seedu/address/model/deliverable/deliverable/Deliverable.java
- src/main/java/seedu/address/model/deliverable/deliverable/Description.java
- src/main/java/seedu/address/model/deliverable/deliverable/Title.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/deliverable/JsonAdaptedDeliverable.java
- src/main/java/seedu/address/ui/DeliverableCard.java
- src/main/resources/view/DeliverableListCard.fxml
- src/test/java/seedu/address/model/deliverable/deliverable/DeliverableTest.java
- src/test/java/seedu/address/testutil/DeliverableBookBuilder.java
- src/test/java/seedu/address/testutil/DeliverableBuilder.java
- src/test/java/seedu/address/testutil/DeliverableUtil.java
- src/test/java/seedu/address/testutil/TypicalDeliverables.java
-Amend the attributes under deliverable
-Create new java classes for each attribute
-Amend UI files for deliverable
-Implement add deliverable feature
-Implement delete deliverable feature
> Implement Add and Delete deliverable features

- src/main/java/seedu/address/model/util/DateTime.java
- src/test/java/seedu/address/model/util/DateTimeTest.java
DateTime is a field encapsulating a valid date string as a
LocalDateTime. DateTime can take in either a date with time or just a
date only.
DateTime can be compared with other datetime objects based on their
respective values.
> Add DateTime class

- src/main/java/seedu/address/logic/commands/meeting/AddCommand.java
- src/main/java/seedu/address/logic/parser/meeting/AddCommandParser.java
> Minor bug fixes

- src/main/java/seedu/address/logic/commands/meeting/EditCommand.java
- src/main/java/seedu/address/logic/parser/meeting/AddCommandParser.java
- src/main/java/seedu/address/model/meeting/meeting/Meeting.java
- src/main/java/seedu/address/storage/meeting/JsonAdaptedMeeting.java
- Validate order in Meeting's constructor, throw IllegalArgumentException if invalid. 
- Add try and catch blocks for methods dependent on Meeting's constructor.
> Enforce From and To chronological order 

- src/main/java/seedu/address/model/person/AddressBook.java
- src/main/java/seedu/address/model/person/person/Name.java
- src/main/java/seedu/address/model/person/person/UniquePersonList.java
- src/main/java/seedu/address/model/person/util/PersonComparator.java
- src/test/java/seedu/address/model/person/person/NameTest.java
- src/test/java/seedu/address/model/person/person/UniquePersonListTest.java
- src/test/java/seedu/address/model/person/util/PersonComparatorTest.java
> Autosort person list

- docs/DeveloperGuide.md
- docs/SettingUp.md
- docs/Testing.md
- docs/index.md
> Edit various documentations to fit Productiv

- docs/AboutUs.md
- docs/team/gabztcr.md
To edit the components accordingly in another commit
> Duplicate PPP

- src/main/java/seedu/address/logic/LogicDeliverable.java
- src/main/java/seedu/address/logic/LogicDeliverableManager.java
- src/main/java/seedu/address/logic/LogicMeeting.java
- src/main/java/seedu/address/logic/LogicMeetingManager.java
- src/main/java/seedu/address/model/deliverable/DeliverableBook.java
- src/main/java/seedu/address/model/deliverable/ModelDeliverable.java
- src/main/java/seedu/address/model/deliverable/ModelDeliverableManager.java
- src/main/java/seedu/address/model/deliverable/deliverable/UniqueDeliverableList.java
- src/main/java/seedu/address/model/meeting/MeetingBook.java
- src/main/java/seedu/address/model/meeting/ModelMeeting.java
- src/main/java/seedu/address/model/meeting/ModelMeetingManager.java
- src/main/java/seedu/address/model/meeting/meeting/UniqueMeetingList.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/test/java/seedu/address/logic/commands/deliverable/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/meeting/AddCommandTest.java
- Create getters of internalList
- Pass internalList to Calendar constructor 
- Modify the test stub
> Prevent Calendar from updating when Find command is executed

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/deliverable/AddCommand.java
- src/main/java/seedu/address/logic/commands/deliverable/ClearCommand.java
- src/main/java/seedu/address/logic/commands/deliverable/EditCommand.java
- src/main/java/seedu/address/logic/commands/deliverable/ListCommand.java
- src/main/java/seedu/address/logic/commands/deliverable/ViewCommand.java
- src/main/java/seedu/address/logic/commands/meeting/AddCommand.java
- src/main/java/seedu/address/logic/commands/meeting/ClearCommand.java
- src/main/java/seedu/address/logic/commands/meeting/EditCommand.java
- src/main/java/seedu/address/logic/commands/meeting/ListCommand.java
- src/main/java/seedu/address/logic/commands/meeting/ViewCommand.java
- src/main/java/seedu/address/logic/commands/mode/HelpCommand.java
- src/main/java/seedu/address/logic/commands/mode/SwitchCommand.java
- src/main/java/seedu/address/logic/commands/person/AddCommand.java
- src/main/java/seedu/address/logic/commands/person/ClearCommand.java
- src/main/java/seedu/address/logic/commands/person/FindCommand.java
- src/main/java/seedu/address/logic/commands/person/ListCommand.java
- src/main/java/seedu/address/logic/commands/person/ViewCommand.java
- src/test/java/seedu/address/logic/commands/person/FindCommandTest.java
- Update tenses
- Punctuation 
- new lines 
- Update date and contact in examples
> Standardize message prompts

- docs/UserGuide.md
- Add new line to display table properly in HTML
> Fix command summary table 

- src/main/java/seedu/address/model/deliverable/deliverable/UniqueDeliverableList.java
- src/main/java/seedu/address/model/meeting/meeting/UniqueMeetingList.java
- Unwrap FXCollectionArrayList() from internalList
- Return internalList only instead
> Fix no-update issue for Calendar 

- src/main/java/seedu/address/MainApp.java
Fixes #174 
- Change person to contact
> Minor Logger info change

- src/main/java/seedu/address/model/meeting/meeting/Meeting.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/ui/MeetingCard.java
- src/main/java/seedu/address/ui/MeetingDetailsPanel.java
- src/main/resources/view/MeetingDetailsPanel.fxml
- src/main/resources/view/MeetingListCard.fxml
- src/main/resources/view/MeetingListPanel.fxml
- src/test/java/seedu/address/logic/commands/meeting/CommandTestUtil.java
- src/test/java/seedu/address/model/meeting/meeting/MeetingTest.java
- src/test/java/seedu/address/testutil/TypicalMeetings.java
- Combine Ui From and To columns to Date Time column
- From must be strictly less than To
> Meeting from to update

- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/ui/MainWindow.java
Version update to 1.4
Unable to implement logger for help window without duplicates.
> Fix logger for modes and update version

- docs/UserGuide.md
> Update UG - Include Dashboard component

- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/UiManager.java
- src/main/resources/view/CalendarListDeliverableCard.fxml
- src/main/resources/view/CalendarListMeetingCard.fxml
- src/main/resources/view/DeliverableListCard.fxml
- src/main/resources/view/MeetingListCard.fxml
- src/main/resources/view/PersonListCard.fxml
- src/test/java/seedu/address/logic/LogicModeManagerTest.java
- src/test/java/seedu/address/logic/commands/mode/SwitchCommandTest.java
- src/test/java/seedu/address/logic/parser/mode/ModeParserTest.java
> Truncate list and remove status bar

- docs/DeveloperGuide.md
- docs/SettingUp.md
- docs/UserGuide.md
Close #223 (Java 11)
Close #220 (DG Appendix)
> Update DG appendix

- docs/UserGuide.md
- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/deliverable/ClearCommand.java
- src/main/java/seedu/address/logic/commands/deliverable/ListCommand.java
- src/main/java/seedu/address/logic/commands/meeting/ClearCommand.java
- src/main/java/seedu/address/logic/commands/meeting/ListCommand.java
- src/main/java/seedu/address/logic/commands/person/ClearCommand.java
- src/main/java/seedu/address/logic/commands/person/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/person/EditCommand.java
- src/main/java/seedu/address/logic/commands/person/ListCommand.java
- src/main/java/seedu/address/logic/commands/person/ViewCommand.java
- src/main/java/seedu/address/model/person/AddressBook.java
- src/main/java/seedu/address/model/person/ModelPerson.java
- src/main/java/seedu/address/model/person/ModelPersonManager.java
- src/main/java/seedu/address/model/person/person/UniquePersonList.java
- src/test/java/seedu/address/logic/LogicPersonManagerTest.java
- src/test/java/seedu/address/logic/commands/deliverable/ClearCommandTest.java
- src/test/java/seedu/address/logic/commands/person/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/person/ClearCommandTest.java
- src/test/java/seedu/address/logic/commands/person/DeleteCommandTest.java
- src/test/java/seedu/address/logic/commands/person/EditCommandTest.java
> Disallow clearing/listing of empty lists

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/address/commons/core/Messages.java
- src/main/resources/view/ProjectCompletionStatusPanel.fxml
Fixes #226 + amend UG to include the ability to empty an optional field
> Update DG's use cases and user stories
